kind = "web"
previewPath = "/"
title = "TAARIFA_ID"
version = "1.0.0"
id = "artifacts/taarifa-id"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 21711

[services.development]
run = "pnpm --filter @workspace/taarifa-id run dev"

[services.production]

[services.production.build]
args = ["pnpm", "--filter", "@workspace/taarifa-id", "run", "build"]

[services.production.build.env]
NODE_ENV = "production"

[services.production.run]
args = ["pnpm", "--filter", "@workspace/taarifa-id", "run", "start"]

[services.production.run.env]
PORT = "21711"
NODE_ENV = "production"

[services.env]
PORT = "21711"
BASE_PATH = "/"
